language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-py-microlib' ]; then cd .. && eval "mv $currentfolder generator-py-microlib" && cd generator-py-microlib; fi

